### ISSUE TITLE
Error on generate svg file

### ISSUE THREAD

**Issue by zgr0629** [yihong0618/running_page#23]
When sync my nike data, there some warning:
```
...
...
...
The activity 1b611a53-e448-4ddb-a9a5-fd6264cfb3ea doesn't contain metrics information
The activity b0be4df9-b9e4-47d9-a439-f1a4d6f75de3 doesn't contain metrics information
The activity 310f5826-a6d9-4995-9e93-b3449aa4b35d doesn't contain metrics information
...
...
...
```

and gets an error when generate svg file

```
Run python scripts/gen_svg.py --from-db --title "Gary's Running" --type github --athlete "Gary" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
179
179
Creating poster of type github with 165 tracks and storing it in file assets/github.svg...
179
179
Creating poster of type grid with 17 tracks and storing it in file assets/grid.svg...
Traceback (most recent call last):
  File "scripts/gen_svg.py", line 259, in <module>
    main()
  File "scripts/gen_svg.py", line 253, in main
    p.draw(drawers[args.type], args.output)
  File "/home/runner/work/running_page/running_page/scripts/gpxtrackposter/poster.py", line 111, in draw
    self.__draw_tracks(d, XY(self.width - 20, self.height - 30 - 30), XY(10, 30))
  File "/home/runner/work/running_page/running_page/scripts/gpxtrackposter/poster.py", line 131, in __draw_tracks
    self.tracks_drawer.draw(d, size, offset)
  File "/home/runner/work/running_page/running_page/scripts/gpxtrackposter/grid_drawer.py", line 50, in draw
    offset + 0.05 * XY(cell_size, cell_size) + p,
  File "/home/runner/work/running_page/running_page/scripts/gpxtrackposter/grid_drawer.py", line 64, in _draw_track
    color = self.color(self.poster.length_range_by_date, tr.length, has_special)
  File "/home/runner/work/running_page/running_page/scripts/gpxtrackposter/tracks_drawer.py", line 34, in color
    assert length_range.contains(length)
AssertionError
Error: Process completed with exit code 1.
```

I'm a total python newbie and don't know what's wrong.

**Comment by yihong0618** [comment]
Because some of your activities does not contain the length. 
Cna you use this script in the local env and try again and to see what happens.
```python
python scripts/gen_svg.py --from-db --title "${{ env.TITLE_GRID }}" --type grid --athlete "${{ env.ATHLETE }}"  --output assets/grid.svg --use-localtime
```

**Comment by yihong0618** [comment]
@zgr0629 
If it is still not work I will try to drop the `assert`  and pass the error.

**Comment by zgr0629** [comment]
Result of script you give:
```
python3 scripts/gen_svg.py --from-db --title "Gary's Running" --type grid --athlete "Gary"  --output assets/grid.svg --use-localtime
179
179
Creating poster of type grid with 160 tracks and storing it in file assets/grid.svg...
```

Result of script in github action run:
```
python3 scripts/gen_svg.py --from-db --title "Gary's Running" --type github --athlete "Gary" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
179
179
Creating poster of type github with 165 tracks and storing it in file assets/github.svg...
```


Both command can generate correct svg file on my machine.(Python 3.7.9)
Do you need any further information?

**Comment by yihong0618** [comment]
Cool @zgr0629 glad to here you got correct svg file.
I think you can change the length --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5 to make it color that not caused the problem.
No future info need~
