### ISSUE TITLE
ModuleNotFoundError: No module named 'gpxpy'

### ISSUE THREAD

**Issue by Theoshen** [yihong0618/running_page#260]
![image](https://user-images.githubusercontent.com/53144901/175451757-b81430e5-da9e-4edc-89ea-a13c82c8fc0d.png)
运行脚本的时候说无法引入gpxpy的库
但是pip3 install成功了的 这是咋回事呀

**Comment by yihong0618** [comment]
看起来你 python3 和 python3.9 用的不是一个 pip
你可以试试 
`python3.9 -m pip install -r .....`

**Comment by yihong0618** [comment]
先关掉了哈，有问题随时 reopen

**Comment by sauchye** [comment]
```
执行
 python3 scripts/tcx_to_strava_sync.py x x x

报错

Traceback (most recent call last):
  File "scripts/tcx_to_strava_sync.py", line 6, in <module>
    from strava_sync import run_strava_sync
  File "/Users/sauchye/Workspace/dev/tools/running_page/scripts/strava_sync.py", line 5, in <module>
    from generator import Generator
  File "/Users/sauchye/Workspace/dev/tools/running_page/scripts/generator/__init__.py", line 6, in <module>
    from gpxtrackposter import track_loader
  File "/Users/sauchye/Workspace/dev/tools/running_page/scripts/gpxtrackposter/track_loader.py", line 20, in <module>
    from .track import Track
  File "/Users/sauchye/Workspace/dev/tools/running_page/scripts/gpxtrackposter/track.py", line 16, in <module>
    from tcxparser import TCXParser
ModuleNotFoundError: No module named 'tcxparser'
```

**Comment by yihong0618** [comment]
@sauchye 
pip install python-tcxparser

**Comment by yihong0618** [comment]
@sauchye

**Comment by sauchye** [comment]
拉了最新代码，似乎没有tcx_to_strava_sync.py 文件夹
 can't open file 'scripts/tcx_to_strava_sync.py': [Errno 2] No such file or directory
@yihong0618

**Comment by yihong0618** [comment]
有的，你检查一下。。。
![image](https://user-images.githubusercontent.com/15976103/196037361-7c82d973-a228-4ad4-9a79-d1b1167d3556.png)

**Comment by sauchye** [comment]
```
Need to load all tcx files maybe take some time
Something wrong to get last time err: 'NoneType' object has no attribute
'get_activities'
Traceback (most recent call last):
  File "scripts/tcx_to_strava_sync.py", line 59, in <module>
    upload_file_to_strava(client, tcx_file, "tcx")
  File "/Users/sauchye/Workspace/dev/tools/running_page/scripts/utils.py", line 71, in upload_file_to_strava
    r = client.upload_activity(activity_file=f, data_type=data_type)
AttributeError: 'NoneType' object has no attribute 'upload_activity'
````

**Comment by yihong0618** [comment]
@sauchye 修复了，又提交了一次再次抱歉。。。

**Comment by sauchye** [comment]
老哥牛批

```
Need to load all tcx files maybe take some time
False
Something wrong to get last time err: Unauthorized: Authorization Error:
[{'resource': 'AccessToken', 'field': 'activity:read_permission', 'code':
'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
```

**Comment by yihong0618** [comment]
@sauchye 这个是 starva 的问题了，需要按照 README 中 starve 部分的步骤，否则是没有写的权限的。

**Comment by sauchye** [comment]
好的，非常感谢老哥🎈🎈

**Comment by yihong0618** [comment]
客气了
