### ISSUE TITLE
TCX_to_Strava

### ISSUE THREAD

**Issue by cigar** [yihong0618/running_page#313]
RUN: 
python3 scripts/strava_sync.py xxxxx xxx xxx

Access ok
Start syncing
Traceback (most recent call last):
  File "/Users/liantang/Works/docker/running_page/scripts/strava_sync.py", line 25, in <module>
    run_strava_sync(options.client_id, options.client_secret, options.refresh_token)
  File "/Users/liantang/Works/docker/running_page/scripts/strava_sync.py", line 12, in run_strava_sync
    generator.sync(False)
  File "/Users/liantang/Works/docker/running_page/scripts/generator/__init__.py", line 54, in sync
    for run_activity in self.client.get_activities(**filters):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/client.py", line 1658, in __next__
    return self.next()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/client.py", line 1664, in next
    self._fill_buffer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/client.py", line 1635, in _fill_buffer
    raw_results = self.result_fetcher(page=self._page, per_page=self.per_page)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/protocol.py", line 292, in get
    return self._request(url, params=params, check_for_errors=check_for_errors)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/protocol.py", line 214, in _request
    self._handle_protocol_error(raw)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stravalib/protocol.py", line 261, in _handle_protocol_error
    raise exc_class(msg, response=response)
stravalib.exc.AccessUnauthorized: Unauthorized: Authorization Error: [{'resource': 'AccessToken', 'field': 'activity:read_permission', 'code': 'missing'}]

**Comment by yihong0618** [comment]
@cigar 
报错应该是没有写的权限，
请参考 readme 中的 strava 部分，申请所有权限的 strava api token

**Comment by yihong0618** [comment]
@cigar 先关了哈
