### ISSUE TITLE
feat: gpx to strava 

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#323]
as we discussed https://github.com/yihong0618/running_page/discussions/322

**Comment by yihong0618** [comment]
@ben-29 @sauchye 增加了 gpx_to_strava_sync 可以尝试了。

**Comment by sauchye** [comment]
```
Need to load all gpx files maybe take some time
Traceback (most recent call last):
  File "scripts/gpx_to_strava_sync.py", line 55, in <module>
    to_upload_time_list, to_upload_dict = get_to_generate_files(last_time)
  File "scripts/gpx_to_strava_sync.py", line 25, in get_to_generate_files
    gpx_files_dict = {
  File "scripts/gpx_to_strava_sync.py", line 28, in <dictcomp>
    if int(i[0].get_time_bounds()[0].timestamp()) > last_time
AttributeError: 'NoneType' object has no attribute 'timestamp'
```
我附件了一个 @yihong0618 
[200566911.gpx.zip](https://github.com/yihong0618/running_page/files/9799613/200566911.gpx.zip)

**Comment by yihong0618** [comment]
@sauchye 你有的 gpx 是空的， 我加个判断。

**Comment by yihong0618** [comment]
@sauchye 你给我的附件不是 gpx file, 是 tcx 改的 gpx....

**Comment by yihong0618** [comment]
咕咚 + 悦跑圈 导出的是 gpx.

**Comment by yihong0618** [comment]
@sauchye 测试了下，没问题。。。

**Comment by yihong0618** [comment]
1. 用 running_page 导出的 咕咚，悦跑圈都是 gpx files
2. 如果是 nike 官方导出的是 tcx
3. tcx 用 tcx_to_strava_sync, gpx 用 gpx_to_strava_sync

**Comment by sauchye** [comment]
感谢老哥不厌其烦，快速响应！
这是joyrun导出的数据，同步还是有些问题，我附上文件。
步骤：

```
python3 scripts/gpx_sync.py

python3 scripts/gpx_to_strava_sync.py xxx xxx xxx 
```

```
Need to load all gpx files maybe take some time
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gpxpy/parser.py", line 132, in parse
    root = mod_etree.XML(self.xml, mod_etree.XMLParser(remove_comments=True))
  File "src/lxml/etree.pyx", line 3233, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/gpx_to_strava_sync.py", line 58, in <module>
    to_upload_time_list, to_upload_dict = get_to_generate_files(last_time)
  File "scripts/gpx_to_strava_sync.py", line 27, in get_to_generate_files
    gpx_files.append((mod_gpxpy.parse(r), file_path))
  File "/usr/local/lib/python3.7/site-packages/gpxpy/__init__.py", line 39, in parse
    return parser.parse(version)
  File "/usr/local/lib/python3.7/site-packages/gpxpy/parser.py", line 146, in parse
    raise mod_gpx.GPXXMLSyntaxException('Error parsing XML: %s' % str(e), e)
gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: Document is empty, line 1, column 1 (<string>, line 1)

```
[GPX_OUT.zip](https://github.com/yihong0618/running_page/files/9800779/GPX_OUT.zip)

**Comment by yihong0618** [comment]
@sauchye 尝试修复了，你拉下最新代码试试？

**Comment by sauchye** [comment]
Strava API Rate Limit Exceeded. Retry after 100 seconds

Strava API Rate Limit Timeout. Retry in 799.491622 seconds

一直开着等跑完，咕咚再同步，感谢yihong大哥🎈🎈

**Comment by sauchye** [comment]
yihong早  README 也同步更新吧，避免产生同步完，数据实际没有同步到strava
```
python3(python) scripts/tcx_to_strava_sync.py xxx xxx xxx --all

等待时间限制（这里是strava接口请求限制：[100 每 15 分钟的请求， 1000 每日](https://developers.strava.com/docs/#rate-limiting)），不要关闭终端，这里会自动执行下一组上传数据
Strava API Rate Limit Exceeded. Retry after 100 seconds
Strava API Rate Limit Timeout. Retry in 799.491622 seconds

```

**Comment by yihong0618** [comment]
@sauchye 有兴趣帮我加一下么？
需要加的
- nike_to_strava
- tcx_to_strava
- gpx_to_strava
---
README and README-CN

**Comment by sauchye** [comment]
好的晚点 我看看 😂

**Comment by yihong0618** [comment]
感谢，都一样，这几个哈哈

**Comment by yihong0618** [comment]
@sauchye 感谢。
