### ISSUE TITLE
Garmin sync error

### ISSUE THREAD

**Issue by shaonianche** [yihong0618/running_page#504]
- Garmin modified the interface verification

![error](https://github.com/yihong0618/running_page/assets/16186646/110bce8f-41a5-403f-a7d1-672d2450c904)

**Comment by app4g** [comment]
same here.. :-(

**Comment by yihong0618** [comment]
yes we know that issue, will try to fix it these days

**Comment by naosense** [comment]
今天刚出现的，昨天还是好的

**Comment by yihong0618** [comment]
maybe need some big change, so we need to wait....

**Comment by yihong0618** [comment]
修复了，按照如下步骤实验

- git pull
- python -m pip install -U git+https://github.com/yihong0618/garth.git
- get `python run_page/garmin_sync.py ${email} ${password}` if cn `python run_page/garmin_sync.py ${email} ${password} --is-cn` to get the secret_string
- python run_page/garmin_sync.py ${secret_string} --is-cn
- 修改 Actions 的 secret

**Comment by yihong0618** [comment]
按照我的能成功么？

**Comment by naosense** [comment]
> 按照我的能成功么？

可以了

**Comment by weaming** [comment]
可惜是 python 版本，ts 版本怎么修

**Comment by misaka9981** [comment]
> * python run_page/garmin_sync.py ${email} ${password} --is-cn

我的报错403了。
`
 python3 scripts/garmin_sync.py xxx@gmail.com xxx --is-cn 
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_exceptions.py", line 339, in map_exceptions
    yield
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1500, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 200, in arequest
    response = await connection.arequest(
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_async/connection.py", line 87, in arequest
    self.socket = await self._open_socket(timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_async/connection.py", line 108, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 240, in open_tcp_stream
    return SocketStream(
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 150, in fetch_data
    response = await self.req.get(url, headers=self.headers)
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1546, in get
    return await self.request(
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1364, in request
    response = await self.send(
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1397, in send
    response = await self._send_handling_auth(
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1435, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1467, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 1500, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_exceptions.py", line 356, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 154, in fetch_data
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_models.py", line 1070, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 403 Client Error: Forbidden for url: https://connect.garmin.cn/proxy/activitylist-service/activities/search/activities?start=0&limit=100
For more information check: https://httpstatuses.com/403

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 398, in <module>
    loop.run_until_complete(future)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 327, in download_new_activities
    activity_ids = await get_activity_id_list(client)
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 297, in get_activity_id_list
    activities = await client.get_activities(start, 100)
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 180, in get_activities
    return await self.fetch_data(url)
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 169, in fetch_data
    await self.fetch_data(url, retrying=True)
  File "/Users/cxy/Documents/running_page/scripts/garmin_sync.py", line 162, in fetch_data
    raise GarminConnectConnectionError("Error connecting") from err
__main__.GarminConnectConnectionError: Error connecting
/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py:1778: UserWarning: Unclosed <httpx.AsyncClient object at 0x1077562b0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
`

**Comment by yihong0618** [comment]
just check it work fine here, and its based on https://github.com/matin/garth you can use this to check
its ssl error...please check internet, and ssl things

**Comment by zerosrat** [comment]
<img width="950" alt="image" src="https://github.com/yihong0618/running_page/assets/8179987/33fc1596-1f30-4bc8-aa73-15d80e17d0c2">

- 换用了 scret 去请求 garmin 数据，当天没问题，第 2 天会有问题，怀疑是 secret 过期了？

- [code](https://github.com/yihong0618/running_page/blob/320e8532b932618e3c0fdd94279a1438d50b6505/.github/workflows/run_data_sync.yml#L116) 这里是不是应该先获取 secret_string 再用实时获取的 secret 去请求数据呢？

**Comment by yihong0618** [comment]
@zerosrat 确实，我这里研究下。

**Comment by yihong0618** [comment]
@zerosrat 那样的话我害怕多次请求。。。。容易 ban 号，我研究下为什么

**Comment by yihong0618** [comment]
@zerosrat 修复了，拉取最新代码就行

**Comment by efish2002** [comment]
[requirements.txt](https://github.com/efish2002/running_page/blob/master/requirements.txt) 中添加了garth 出现下面的错误
![image](https://github.com/yihong0618/running_page/assets/10509616/0db08fab-6619-40c7-b698-1fda76b65f0a)

**Comment by yihong0618** [comment]
> [requirements.txt](https://github.com/efish2002/running_page/blob/master/requirements.txt) 中添加了garth 出现下面的错误
> ![image](https://user-images.githubusercontent.com/10509616/273354834-0db08fab-6619-40c7-b698-1fda76b65f0a.png)

需要大于 3.8

**Comment by efish2002** [comment]
python run_page/garmin_sync.py ${{ secrets.GARMIN_SECRET_STRING_CN }}  --only-run --is-cn
secrets.GARMIN_SECRET_STRING_CN 这个是要在secret中自己定义吗？ 格式是什么呢？ “佳明的用户名 密码” 吗？
![image](https://github.com/yihong0618/running_page/assets/10509616/044a6476-454f-4245-a3b2-863d5b2bd9cc)

**Comment by shaonianche** [comment]
> secrets.GARMIN_SECRET_STRING_CN 这个是要在secret中自己定义吗？ 格式是什么呢？

是需要自己定义的，这是个使用用戶名密码获取的字符串。步骤参见下文：
https://github.com/yihong0618/running_page/issues/504#issuecomment-1735815795

**Comment by outcastveron** [comment]
本地获取secret的时候报错，麻烦看下


PS C:\Users\limia\Downloads\running_page-master\run_page> python get_garmin_secret.py ${XXXX@hotmail.com} ${XXXX} --is-cn
Traceback (most recent call last):
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\garth\http.py", line 127, in request
    self.last_resp.raise_for_status()
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sso.garmin.cn/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\limia\Downloads\running_page-master\run_page\get_garmin_secret.py", line 18, in <module>
    garth.login(options.email, options.password)
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\garth\http.py", line 148, in login
    self.oauth1_token, self.oauth2_token = sso.login(*args, client=self)
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\garth\sso.py", line 79, in login
    client.post(
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\garth\http.py", line 139, in post
    return self.request("POST", *args, **kwargs)
  File "C:\Users\limia\AppData\Local\Programs\Python\Python310\lib\site-packages\garth\http.py", line 129, in request
    raise GarthHTTPError(
garth.exc.GarthHTTPError: Error in request: 401 Client Error: Unauthorized for url: https://sso.garmin.cn/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed

**Comment by efish2002** [comment]
> > secrets.GARMIN_SECRET_STRING_CN 这个是要在secret中自己定义吗？ 格式是什么呢？
> 
> 是需要自己定义的，这是个使用用戶名密码获取的字符串。步骤参见下文： [#504 (comment)](https://github.com/yihong0618/running_page/issues/504#issuecomment-1735815795)

成功了，谢谢

**Comment by shaonianche** [comment]
检查一下您的用戶名密码是否正确，运行脚本的时候可以用引号包含一下用戶名密码
python get_garmin_secret.py "XXXX@hotmail.com"  "XXXX" --is-cn

**Comment by shaonianche** [comment]
> 本地获取secret的时候报错，麻烦看下
检查一下您的用戶名密码是否正确，运行脚本的时候可以用引号包含一下用戶名密码
python get_garmin_secret.py "[XXXX@hotmail.com](mailto:XXXX@hotmail.com)" "XXXX" --is-cn

**Comment by outcastveron** [comment]
@shaonianche 感谢回复，已经解决！
