### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by xiao990720** [yihong0618/running_page#519]
Error: EACCES: permission denied, mkdir '/Users/AADocuments/run/running_page/node_modules/.vite/deps_temp_d9646a69'
    at Object.mkdirSync (node:fs:1398:3)
    at runOptimizeDeps (file:///Users/AA/Documents/run/running_page/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.7_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45747:10)
    at file:///Users/AA/Documents/run/running_page/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.7_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45129:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

出现了两次，换文件夹git后也这样
然后网页也打不开

macos系统

**Comment by yihong0618** [comment]
sudo?
