### ISSUE TITLE
我们需要个升级指南

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#532]
如何升级到 2.0

**Comment by shog86** [comment]
可以参考lobechat vercel部署后用action自动推到vercel实现升级的办法

**Comment by MingchaoShi** [comment]
同意。本小白在2022年折腾一番终于从keep中导出了gpx文件，现在下载了2.0想再次导出，提示：

Traceback (most recent call last):
  File "D:\running_page\run_page\keep_sync.py", line 232, in <module>
    run_keep_sync(options.phone_number, options.password, options.with_gpx)
  File "D:\running_page\run_page\keep_sync.py", line 213, in run_keep_sync
    new_tracks = get_all_keep_tracks(email, password, old_tracks_ids, with_download_gpx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\running_page\run_page\keep_sync.py", line 149, in get_all_keep_tracks
    s, headers = login(s, email, password)
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

请问这个是登录失败了吗？

**Comment by shog86** [comment]
如果github page部署，是不是直接pull the latest，再重新发布page就能更新了？（但可能自己fork之后做的修改是不是也会被覆盖？不知道Github fork之后的repo跟进pull的校验机制是啥样的）

**Comment by MingchaoShi** [comment]
> 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确

谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。

**Comment by yihong0618** [comment]
> > 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确
> 
> 谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。

参考 README 或者在 issue 里搜索骑行。

**Comment by MingchaoShi** [comment]
> > > 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确
> > 
> > 
> > 谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。
> 
> 参考 README 或者在 issue 里搜索骑行。

谢谢！我搜索了keep骑行，没有找到同类的问题。我按其中的某人建议删除了GPX文件和data.db文件，重新导出keep骑行数据（keep_sync.py中的running已经修改为cycling），导出了552个文件，查看最新的GPX文件是2023年8月19日的记录，而在keep里2023年此日期后还有3条数据，以及2024年有13条数据，都没有导出。

**Comment by MingchaoShi** [comment]
> > > > 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确
> > > 
> > > 
> > > 谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。
> > 
> > 
> > 参考 README 或者在 issue 里搜索骑行。
> 
> 谢谢！我搜索了keep骑行，没有找到同类的问题。我按其中的某人建议删除了GPX文件和data.db文件，重新导出keep骑行数据（keep_sync.py中的running已经修改为cycling），导出了552个文件，查看最新的GPX文件是2023年8月19日的记录，而在keep里2023年此日期后还有3条数据，以及2024年有13条数据，都没有导出。

我又导了一次数据，仍然缺了最近的16条数据，我发现在执行keep_sync.py后，有16条这样的提示：
parsing keep id 57937fe03d2d702505bf4834_9223370318662097313_cy
Something wrong paring keep id 57937fe03d2d702505bf4834_9223370318662097313_cyInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4

我问了AI，回答说“Base64编码字符串在解码时不符合Base64的编码规则”，我也不太懂是keep返回的数据编码有变化？

**Comment by yihong0618** [comment]
> > > > > 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确
> > > > 
> > > > 
> > > > 谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。
> > > 
> > > 
> > > 参考 README 或者在 issue 里搜索骑行。
> > 
> > 
> > 谢谢！我搜索了keep骑行，没有找到同类的问题。我按其中的某人建议删除了GPX文件和data.db文件，重新导出keep骑行数据（keep_sync.py中的running已经修改为cycling），导出了552个文件，查看最新的GPX文件是2023年8月19日的记录，而在keep里2023年此日期后还有3条数据，以及2024年有13条数据，都没有导出。
> 
> 我又导了一次数据，仍然缺了最近的16条数据，我发现在执行keep_sync.py后，有16条这样的提示： parsing keep id 57937fe03d2d702505bf4834_9223370318662097313_cy Something wrong paring keep id 57937fe03d2d702505bf4834_9223370318662097313_cyInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
> 
> 我问了AI，回答说“Base64编码字符串在解码时不符合Base64的编码规则”，我也不太懂是keep返回的数据编码有变化？

这四条无法解析，不是你的问题 @ben-29 对吧？

**Comment by ben-29** [comment]
> > > > > 是。 @MingchaoShi 不需要再次导出，你把之前导出的 gpx files 拷贝过来就行（你确认下用户名密码正确
> > > > 
> > > > 
> > > > 谢谢！我是想追加上次导出之后的GPX文件到本地。我发现是密码错误并已经解决了问题。但是现在导出的数据里并没有2024年的数据（我确定2024年有骑行数据），不知原因在哪里。
> > > 
> > > 
> > > 参考 README 或者在 issue 里搜索骑行。
> > 
> > 
> > 谢谢！我搜索了keep骑行，没有找到同类的问题。我按其中的某人建议删除了GPX文件和data.db文件，重新导出keep骑行数据（keep_sync.py中的running已经修改为cycling），导出了552个文件，查看最新的GPX文件是2023年8月19日的记录，而在keep里2023年此日期后还有3条数据，以及2024年有13条数据，都没有导出。
> 
> 我又导了一次数据，仍然缺了最近的16条数据，我发现在执行keep_sync.py后，有16条这样的提示： parsing keep id 57937fe03d2d702505bf4834_9223370318662097313_cy Something wrong paring keep id 57937fe03d2d702505bf4834_9223370318662097313_cyInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
> 
> 我问了AI，回答说“Base64编码字符串在解码时不符合Base64的编码规则”，我也不太懂是keep返回的数据编码有变化？

@MingchaoShi  我登录我账号测试是正常都能获取，不过我的数据最迟是23年的。
有可能 keep 改了新数据的加密方式，方便把你的 登陆态（不含账号密码信息，不过我能获取你的跑步记录, 我只会拿来 debug）发我看看是什么情况吗？
https://github.com/yihong0618/running_page/blob/38ad7a3129ced7026bcade2621d6cd349e88107d/run_page/keep_sync.py#L49
在这里加一行，然后运行 keep_sync 把输出的 token: xxxx 复制发我邮箱: ben_29@live.com
```
        print(f'token: {token}')
```

**Comment by ben-29** [comment]
@MingchaoShi 你的版本是久得，拉最新代码重新执行即可

**Comment by MingchaoShi** [comment]
> @MingchaoShi 你的版本是久得，拉最新代码重新执行即可

更新代码后搞定了，谢谢哈！

**Comment by phh95** [comment]
我来补充一个不完全的running_page2.0升级指南，用白板记录了我升级过程中遇到的一些问题和解决方法，希望能帮到稍微有点技术基础的朋友  

点击链接加入boardmix中的文件「running_page1.0升级到2.0说明」
[https://boardmix.cn/app/share/CAE.COLp8gsgASoQh4b_ktr9t4m1jZVMS754vjAGQAE/C6XItL](https://boardmix.cn/app/share/CAE.COLp8gsgASoQh4b_ktr9t4m1jZVMS754vjAGQAE/C6XItL)
