### ISSUE TITLE
悦跑圈数据导出时出现问题，还是网络问题

### ISSUE THREAD

**Issue by Xiaoshizi1024** [yihong0618/running_page#676]
之前探索一段时间，遇到问题，暂时放下这个事情了，今天重新搞又遇到不一样的问题。 #664     

### 今日份探索记录  

**情况1：在不开代理的情况下出现错误：**  
 
``` 
Traceback (most recent call last):
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 372, in <module>
    tracks = j.get_all_joyrun_tracks(old_tracks_ids, options.with_gpx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 325, in get_all_joyrun_tracks
    run_ids = self.get_runs_records_ids()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 166, in get_runs_records_ids
    return [i["fid"] for i in r.json()["datas"]]
                              ~~~~~~~~^^^^^^^^^
KeyError: 'datas' 
```   

**情况2：在开了代理之后的问题如下：**  

```   
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.thejoyrun.com', port=443): Max retries exceeded with url: /userRunList.aspx (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 372, in <module>
    tracks = j.get_all_joyrun_tracks(old_tracks_ids, options.with_gpx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 325, in get_all_joyrun_tracks
    run_ids = self.get_runs_records_ids()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JoyRundateto\running_page-master\run_page\joyrun_sync.py", line 159, in get_runs_records_ids
    r = self.session.post(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python312\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.thejoyrun.com', port=443): Max retries exceeded with url: /userRunList.aspx (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
```   
Ai解析说我没有错误在于
1. ModuleNotFoundError: No module named 'pandas' 
2.  requests.exceptions.SSLError 和 urllib3.exceptions.SSLError    

我已看到了，我电脑已安装了pandas。以及requests 和 urllib3 库  

发现两个问题其实指向的都是这个获取用户运动记录的代码： 
但是我看代码好像已经影响成功了？还是说没有通过验证呢? 

``` 
    def get_runs_records_ids(self):
        payload = {
            "year": 0,
        }
        r = self.session.post(
            f"{self.base_url}/userRunList.aspx",
            data=payload,
            auth=self.auth.reload(payload),
        )
        if not r.ok:
            raise Exception("get runs records error")
        return [i["fid"] for i in r.json()["datas"]]
```
  
网络导致了代码错误不一样，我应该如何解决呢，懵~

**Comment by yihong0618** [comment]
不开代理的时候错误是对的。没找到你的记录。请问你的是跑步记录么？还是骑行？

**Comment by Xiaoshizi1024** [comment]
> 不开代理的时候错误是对的。没找到你的记录。请问你的是跑步记录么？还是骑行？

跑步记录，悦跑圈这个软件只有跑步记录，没有骑行记录的。 最近几年没怎么跑了，想把之前的数据导出来。  

![3253bb8c542e76feacedcf99221748d](https://github.com/yihong0618/running_page/assets/32703518/72b0332a-fb14-444e-8817-6ae9779cea4f)
