### ISSUE TITLE
ModuleNotFoundError: No module named 'appdirs'

### ISSUE THREAD

**Issue by uiolee** [yihong0618/running_page#686]
## error

when run `pnpm data:analysis`, get ModuleNotFoundError: No module named 'appdirs'

```bash
$ pnpm data:analysis

> yihong.run@1.0.0 data:analysis D:\running_page
> python3 run_page/gen_svg.py --from-db --type github --output assets/github.svg

Traceback (most recent call last):
  File "D:\running_page\run_page\gen_svg.py", line 6, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
 ELIFECYCLE  Command failed with exit code 1.
```

## env

windows 10
GNU bash, version 5.2.26(1)-release (x86_64-pc-msys)

```bash
$ python -V
Python 3.11.8
```

## pip install 

```bash
$ pip install appdirs --force-reinstall
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting appdirs
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: appdirs
  Attempting uninstall: appdirs
    Found existing installation: appdirs 1.4.4
    Uninstalling appdirs-1.4.4:
      Successfully uninstalled appdirs-1.4.4
Successfully installed appdirs-1.4.4
```

## pip list

```bash
$ pip list
Package               Version
--------------------- --------------
aiofiles              24.1.0
annotated-types       0.7.0
appdirs               1.4.4
arrow                 1.3.0
beautifulsoup4        4.12.3
bitstruct             8.11.1
certifi               2024.6.2
cffi                  1.16.0
charset-normalizer    3.3.2
cloudscraper          1.2.58
colour                0.1.5
et-xmlfile            1.1.0
eviltransform         0.1.1
fit-tool              0.9.13
future                1.0.0
garmin-fit-sdk        21.141.0
garth                 0.4.46
geographiclib         2.0
geopy                 2.4.1
gpxpy                 1.4.2
greenlet              3.0.3
h11                   0.9.0
h3                    3.7.7
haversine             2.8.0
httpcore              0.11.1
httpx                 0.15.5
idna                  3.7
jdcal                 1.4.1
lxml                  4.9.4
markdown-it-py        3.0.0
mdurl                 0.1.2
numpy                 2.0.0
oauthlib              3.2.2
openpyxl              2.5.12
pip                   24.1
polyline              2.0.2
pycparser             2.22
pycryptodome          3.20.0
pydantic              2.7.4
pydantic_core         2.18.4
Pygments              2.18.0
pyparsing             3.1.2
python-dateutil       2.9.0.post0
pytz                  2024.1
PyYAML                6.0.1
requests              2.32.3
requests-oauthlib     1.3.1
requests-toolbelt     1.0.0
rfc3986               1.5.0
rich                  13.7.1
s2sphere              0.2.5
setuptools            65.5.0
six                   1.16.0
sniffio               1.3.1
soupsieve             2.5
SQLAlchemy            2.0.31
stravalib             0.10.4
stravaweblib          0.0.8
svgwrite              1.4.3
tcxreader             0.4.10
tenacity              8.4.1
timezonefinder        6.5.2
types-python-dateutil 2.9.0.20240316
typing_extensions     4.12.2
tzdata                2024.1
tzlocal               5.2
units                 0.7
urllib3               2.2.2
```

**Comment by yihong0618** [comment]
python -m pip install appdirs

**Comment by uiolee** [comment]
It might be a problem of `venv` or `scoop`, I'm not sure.

```bash
$ echo "which python:  $(which python)" ; echo "which python3: $(which python3)"
which python:  /d/Scoop/apps/python311/current/python
which python3: /d/Scoop/shims/python3
```

```bash
$ ./.venv/Scripts/activate

(.venv)
$
```

```bash
(.venv)
$ echo "which python:  $(which python)" ; echo "which python3: $(which python3)"
which python:  /d/dir/running_page/\dir\running_page\.venv/Scripts/python
which python3: /d/Scoop/shims/python3
``` 

```bash
$ pnpm data:analysis

> yihong.run@1.0.0 data:analysis D:\dir\running_page
> python3 run_page/gen_svg.py --from-db --type github --output assets/github.svg

Traceback (most recent call last):
  File "D:\dir\running_page\run_page\gen_svg.py", line 6, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
 ELIFECYCLE  Command failed with exit code 1.
```

```bash
$ python run_page/gen_svg.py --from-db --type github --output assets/github.svg
All tracks: 180
After filter tracks: 180
Creating poster of type github with 150 tracks and storing it in file assets/github.svg...
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
module 'locale' has no attribute 'MON_1'
```
