### ISSUE TITLE
TypeError: Track.to_namedtuple() got an unexpected keyword argument 'run_from'

### ISSUE THREAD

**Issue by arthurfsy2** [yihong0618/running_page#735]
1.今天同步时发生了错误，action1
action1可见[此处](https://github.com/arthurfsy2/workouts_page_fsy/actions/runs/11789426513/job/32838169516)
```cmd
load 1 tracks
Traceback (most recent call last):
  File "/home/runner/work/workouts_page_fsy/workouts_page_fsy/run_page/garmin_sync_cn_global.py", line 129, in <module>
    make_activities_file(SQL_FILE, FIT_FOLDER, JSON_FILE, file_suffix="fit")
  File "/home/runner/work/workouts_page_fsy/workouts_page_fsy/run_page/utils.py", line 53, in make_activities_file
    generator.sync_from_data_dir(data_dir, file_suffix=file_suffix)
  File "/home/runner/work/workouts_page_fsy/workouts_page_fsy/run_page/generator/__init__.py", line 95, in sync_from_data_dir
    self.session, t.to_namedtuple(run_from=file_suffix)
TypeError: Track.to_namedtuple() got an unexpected keyword argument 'run_from'
```
2. 然后看到yihong更新了代码，但是因为是fork了ben的仓库，由于ben暂未更新，我就手动下载并替换了synced_data_file_logger.py、garmin_sync_cn_global.py，但是action执行后还是出错：
action2可见[此处](https://github.com/arthurfsy2/workouts_page_fsy/actions/runs/11791557639/job/32843764776)

不知道是什么原因？

**Comment by yihong0618** [comment]
不能这样替换的，因为有些代码不一致目前

**Comment by arthurfsy2** [comment]
> 不能这样替换的，因为有些代码不一致目前

因为是突然报错了所以才替换的，但是替换后的报错好像是类似的，我到时候重新试一下

**Comment by ben-29** [comment]
@arthurfsy2 同步最新 workouts 代码试试
